name: Build SELFIX Docker Images

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Run Docker Build Script
        run: ./build_docker_images.sh

      - name: Push Docker Images
        run: |
          TIERS=("HomeGuard" "ProSecure" "TrustShield" "PartnerX")
          for TIER in "${TIERS[@]}"; do
            docker push edaotech/selfix-$TIER
          done
